# creates a new KB template for Jekyll

name: support-newkb

on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
        - name: checkout
          uses: actions/checkout@v4

        - name: create a new kb template
          run: |
            wget https://github.com/motetpaper/kbdate-sh/releases/download/v0.2.3/kbdate.deb
            sudo apt install ./kbdate.deb

            git clone https://github.com/motetpaper/newkb-sh


            # new kb in docs
            cd docs
            bash ../newkb-sh/newkb.sh

            cd ..
            pwd

            # cleanup
            rm -rf newkb-sh/
            rm -rf kbdate.deb

        - name: setup git config
          run: |
            pwd
            git config user.name "GitHub Actions Bot"
            git config user.email "<>"

        - name: commit
          run: |
            pwd

            git pull
            git add .

            newstuff=$( git status | grep "Changes to be committed" | sed 's/ //g' )
            echo $newstuff

            echo ${#newstuff}

            if (( ${#newstuff} > 0 )); then
              git commit -m "generated by MOTETPAPER workflow"
              git push origin main
            fi