# updates 'updated' field in front matter

name: support-updkb

on:
  push:
jobs:
  annotate:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
        - name: checkout
          uses: actions/checkout@v4
          with:
            fetch-depth: 2

        - name: update kb front matter UPDATED field
          run: |
            MOTET_DOCS=$GITHUB_WORKSPACE"/docs/"

            ## get kb tools
            git clone https://github.com/motetpaper/bbqkit

            ## make the updater tool executable
            MOTET_UPD=$GITHUB_WORKSPACE"/bbqkit/updkb.js"
            chmod +x $MOTET_UPD
            echo $MOTET_UPD
            
            ## update the KB files that were changed in this commit
            for f in $(git diff --name-only HEAD^1 HEAD */KB*.md); do 
              echo $f;
              KB_PATH=$MOTET_DOCS$(basename $f)
              echo $KB_PATH
              $MOTET_UPD $KB_PATH
            done;

        - name: setup git config
          run: |
            pwd
            git config user.name "GitHub Actions Bot"
            git config user.email "<>"

        - name: commit
          run: |
            pwd

            git pull
            git add .

            newstuff=$( git status | grep "Changes to be committed" | sed 's/ //g' )
            echo $newstuff

            echo ${#newstuff}

            if (( ${#newstuff} > 0 )); then
              git commit -m "generated by MOTETPAPER workflow"
              git push origin main
            fi
